echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "We are learning Git and GitHub"
echo "hii i am swati"
echo "i am devops in Ygminds Batch no-28"
echo "i am from jalgoan"
